package Parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CS = 8;
  public static final int FS = 4;
  public static final int LT = 11;
  public static final int NE = 14;
  public static final int PLUS = 17;
  public static final int LTE = 12;
  public static final int MULTI = 19;
  public static final int COL = 3;
  public static final int FE = 5;
  public static final int IF = 7;
  public static final int GT = 9;
  public static final int ID = 21;
  public static final int CB = 6;
  public static final int GTE = 10;
  public static final int EOL = 16;
  public static final int E = 13;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int MINUS = 18;
  public static final int CONST = 22;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int START = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "START",
  "COL",
  "FS",
  "FE",
  "CB",
  "IF",
  "CS",
  "GT",
  "GTE",
  "LT",
  "LTE",
  "E",
  "NE",
  "ASSIGN",
  "EOL",
  "PLUS",
  "MINUS",
  "MULTI",
  "DIV",
  "ID",
  "CONST"
  };
}

